name: 'Run jsDelivr-Purge'

on: push

jobs:
  jsdelivrpurge:
    permissions:
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@5.6.0
